apiVersion: kafka.strimzi.io/v1
kind: KafkaUser
metadata:
  name: orders-app
  namespace: kafka
  labels:
    strimzi.io/cluster: prod-kafka
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: orders.events.v1
          patternType: literal
        operations:
          - Read
          - Write
          - Describe
      - resource:
          type: group
          name: orders-consumer
          patternType: prefix
        operations:
          - Read
