apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: orders.events.v1
  namespace: kafka
  labels:
    strimzi.io/cluster: prod-kafka
spec:
  partitions: 6
  replicas: 3
  config:
    min.insync.replicas: 2
    retention.ms: 604800000
    cleanup.policy: delete
    segment.bytes: 1073741824
